version: '3.8'

services:
  bff-service:
    build: .
    container_name: bff-app
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    restart: always
